import { Eye, Handshake, ShieldCheck, Target } from "lucide-react";
import { MotionReveal } from "@/components/MotionReveal";

export const metadata = { title: "About", description: "Meet ZS Elite Partners, a multidisciplinary South African business solutions company built around integrated growth." };

export default function About() { return <>
<section className="page-hero section-dark"><div className="shell narrow"><p className="eyebrow">About ZS Elite Partners</p><h1>We don’t simply provide services. <em>We solve business problems.</em></h1><p>One experienced team aligning marketing, promotions, operations and technology around the same business goals.</p></div></section>
<section className="section shell split"><MotionReveal><p className="eyebrow">Who we are</p><h2>A multidisciplinary partner for businesses that want fewer gaps and better execution.</h2></MotionReveal><MotionReveal><p className="lead">ZS Elite Partners helps businesses improve how they market, operate and grow. Rather than outsourcing to multiple disconnected suppliers, clients partner with one team capable of delivering integrated solutions across creative, promotional, software and security needs.</p><p>Our role is not to sell a list of services. It is to understand where the business is trying to go, identify what is getting in the way, and connect the right expertise to create forward motion.</p></MotionReveal></section>
<section className="section section-soft"><div className="shell values-grid"><div className="value-card"><Target/><p className="eyebrow">Mission</p><h3>Make enterprise-level thinking accessible.</h3><p>Help businesses grow sustainably through innovative marketing, professional brand development, powerful technology and people-driven promotional solutions.</p></div><div className="value-card"><Eye/><p className="eyebrow">Vision</p><h3>Become South Africa’s most trusted business growth partner.</h3><p>Build a complete ecosystem where creativity, technology and exceptional service reinforce one another.</p></div></div></section>
<section className="section shell"><p className="eyebrow">Our values</p><div className="value-strip"><div><ShieldCheck/><h3>Integrity</h3><p>Do what is right, especially when nobody is watching.</p></div><div><Handshake/><h3>Loyalty</h3><p>Build long-term partnerships instead of chasing short-term transactions.</p></div><div><Eye/><h3>Vision</h3><p>Solve today’s challenge while preparing the business for tomorrow.</p></div></div></section>
<section className="section section-black"><div className="shell split"><div><p className="eyebrow">Why partner with us</p><h2>Business growth requires more than great marketing.</h2></div><div className="big-list">{["Strategy", "People", "Technology", "Consistency", "Experience", "Execution"].map((x,i)=><div key={x}><span>0{i+1}</span>{x}</div>)}</div></div></section>
</> }
