import Link from "next/link";
import { ArrowRight, ArrowUpRight, Check, Layers3, Sparkles, Users, Workflow } from "lucide-react";
import { MotionReveal } from "@/components/MotionReveal";
import { brands, stats, verticals } from "@/lib/content";
import { prisma } from "@/lib/prisma";

export default async function Home() {
  const posts = await prisma.post.findMany({ where: { published: true }, orderBy: { publishedAt: "desc" }, take: 3 }).catch(() => []);
  return <>
    <section className="hero section-dark"><div className="hero-grid shell"><MotionReveal><div className="eyebrow">Integrated business solutions · South Africa</div><h1>Growth works better when <em>everything works together.</em></h1><p className="hero-copy">ZS Elite Partners combines strategy, creative, people and technology into one connected growth ecosystem — helping businesses market smarter, operate efficiently and scale with confidence.</p><div className="hero-actions"><Link href="/contact" className="button button-light">Book a free consultation <ArrowUpRight size={18}/></Link><Link href="/services" className="text-link">Explore our solutions <ArrowRight size={18}/></Link></div></MotionReveal><div className="hero-art" aria-hidden="true"><div className="orbit orbit-a"></div><div className="orbit orbit-b"></div><div className="hero-monogram">ZS</div><div className="floating-card fc-1"><Sparkles size={18}/><span>Brand<br/>Momentum</span></div><div className="floating-card fc-2"><Workflow size={18}/><span>Smarter<br/>Operations</span></div><div className="floating-card fc-3"><Users size={18}/><span>Real Human<br/>Connection</span></div></div></div><div className="hero-strip shell">{stats.map(s => <div key={s.label}><strong>{s.value}</strong><span>{s.label}</span></div>)}</div></section>

    <section className="section shell split intro"><MotionReveal><p className="eyebrow">Why ZSEP exists</p><h2>Too many suppliers create too many gaps.</h2></MotionReveal><MotionReveal delay={.08}><p className="lead">Marketing agencies often don’t understand operations. Developers may miss the brand. Promotional teams can be disconnected from sales. Consultants may stop at the recommendation.</p><p>ZS Elite Partners was built to bridge those gaps — one strategic partner with context across the whole business.</p><Link className="text-link dark" href="/about">Meet ZS Elite Partners <ArrowRight size={18}/></Link></MotionReveal></section>

    <section className="section section-soft"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Four connected verticals</p><h2>One ecosystem. Built for business growth.</h2></div><p>Start with one challenge or bring us the whole business. Each vertical can stand alone, but the biggest advantage comes when they work together.</p></div><div className="vertical-grid">{verticals.map((v, i) => <MotionReveal key={v.slug} delay={i*.05}><Link href={`/services#${v.slug}`} className="vertical-card"><span className="card-number">{v.number}</span><Layers3/><div><p>{v.eyebrow}</p><h3>{v.title}</h3><span className="card-link">Explore solution <ArrowUpRight size={16}/></span></div></Link></MotionReveal>)}</div></div></section>

    <section className="section shell"><div className="section-heading"><div><p className="eyebrow">How we work</p><h2>From ambiguity to measurable momentum.</h2></div><p>Every engagement is shaped around the same principle: understand the business first, then build the right solution.</p></div><div className="process-line">{["Discover", "Research", "Strategy", "Build", "Launch", "Optimise", "Grow"].map((x, i) => <div key={x}><span>0{i+1}</span><strong>{x}</strong></div>)}</div></section>

    <section className="section section-black"><div className="shell split"><MotionReveal><p className="eyebrow">The outcome</p><h2>Professional identity. Better systems. More confident scale.</h2></MotionReveal><div className="outcome-list">{["Build a professional, consistent identity", "Generate and nurture qualified leads", "Increase customer engagement", "Improve internal operations", "Automate repetitive work", "Create a scalable foundation for growth"].map(x => <div key={x}><Check size={18}/>{x}</div>)}</div></div></section>

    <section className="section shell"><p className="eyebrow">Selected experience</p><h2>Experience across brands, sectors and stages of growth.</h2><div className="brand-cloud">{brands.map(b => <span key={b}>{b}</span>)}</div><div className="note">Brand names reflect company-profile/team experience and are not presented as endorsements.</div></section>

    <section className="section section-soft"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Insights</p><h2>Ideas for businesses building what’s next.</h2></div><Link href="/blog" className="text-link dark">View all insights <ArrowRight size={18}/></Link></div>{posts.length ? <div className="posts-grid">{posts.map(p => <Link className="post-card" href={`/blog/${p.slug}`} key={p.id}><div className="post-image" style={p.coverImage ? { backgroundImage: `url(${p.coverImage})` } : undefined}></div><span>{p.category}</span><h3>{p.title}</h3><p>{p.excerpt}</p></Link>)}</div> : <div className="empty-insights"><p>The insight library is ready. Publish your first article from the admin dashboard.</p><Link href="/admin/login" className="text-link dark">Open admin <ArrowRight size={18}/></Link></div>}</div></section>
  </>;
}
